title: Wasim Tamboli # your name (or website title) here
# the little icon that appears in the browser window's tab
favicon: ./favicon.ico
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  B.E. in Computer Science, Pune University
  <br><br>
  Python Developer, Geospoc
  <br><br>
  <a href="https://www.linkedin.com/in/wt-wasi/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="./pdf/Resume_Wasim.pdf">View My CV</a> 

theme: jekyll-theme-minimal
google_analytics: G-FKHFDRB4SX # your Google Analytics tracking ID here
